
package com.syntrontech.pmo.pmo.member;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Member", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://60.250.13.200/MessageHubWS/Member.asmx?wsdl")
public class Member
    extends Service
{

    private final static URL MEMBER_WSDL_LOCATION;
    private final static WebServiceException MEMBER_EXCEPTION;
    private final static QName MEMBER_QNAME = new QName("http://tempuri.org/", "Member");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://60.250.13.200/MessageHubWS/Member.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEMBER_WSDL_LOCATION = url;
        MEMBER_EXCEPTION = e;
    }

    public Member() {
        super(__getWsdlLocation(), MEMBER_QNAME);
    }

    public Member(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEMBER_QNAME, features);
    }

    public Member(URL wsdlLocation) {
        super(wsdlLocation, MEMBER_QNAME);
    }

    public Member(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEMBER_QNAME, features);
    }

    public Member(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Member(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MemberSoap
     */
    @WebEndpoint(name = "MemberSoap")
    public MemberSoap getMemberSoap() {
        return super.getPort(new QName("http://tempuri.org/", "MemberSoap"), MemberSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MemberSoap
     */
    @WebEndpoint(name = "MemberSoap")
    public MemberSoap getMemberSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "MemberSoap"), MemberSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns MemberSoap
     */
    @WebEndpoint(name = "MemberSoap12")
    public MemberSoap getMemberSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "MemberSoap12"), MemberSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MemberSoap
     */
    @WebEndpoint(name = "MemberSoap12")
    public MemberSoap getMemberSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "MemberSoap12"), MemberSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEMBER_EXCEPTION!= null) {
            throw MEMBER_EXCEPTION;
        }
        return MEMBER_WSDL_LOCATION;
    }

}
