
package com.syntrontech.pmo.pmo.vitalsign;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VitalSign", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://60.250.13.200/MessageHubWS/VitalSign.asmx?wsdl")
public class VitalSign
    extends Service
{

    private final static URL VITALSIGN_WSDL_LOCATION;
    private final static WebServiceException VITALSIGN_EXCEPTION;
    private final static QName VITALSIGN_QNAME = new QName("http://tempuri.org/", "VitalSign");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://60.250.13.200/MessageHubWS/VitalSign.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VITALSIGN_WSDL_LOCATION = url;
        VITALSIGN_EXCEPTION = e;
    }

    public VitalSign() {
        super(__getWsdlLocation(), VITALSIGN_QNAME);
    }

    public VitalSign(WebServiceFeature... features) {
        super(__getWsdlLocation(), VITALSIGN_QNAME, features);
    }

    public VitalSign(URL wsdlLocation) {
        super(wsdlLocation, VITALSIGN_QNAME);
    }

    public VitalSign(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VITALSIGN_QNAME, features);
    }

    public VitalSign(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VitalSign(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VitalSignSoap
     */
    @WebEndpoint(name = "VitalSignSoap")
    public VitalSignSoap getVitalSignSoap() {
        return super.getPort(new QName("http://tempuri.org/", "VitalSignSoap"), VitalSignSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VitalSignSoap
     */
    @WebEndpoint(name = "VitalSignSoap")
    public VitalSignSoap getVitalSignSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "VitalSignSoap"), VitalSignSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns VitalSignSoap
     */
    @WebEndpoint(name = "VitalSignSoap12")
    public VitalSignSoap getVitalSignSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "VitalSignSoap12"), VitalSignSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VitalSignSoap
     */
    @WebEndpoint(name = "VitalSignSoap12")
    public VitalSignSoap getVitalSignSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "VitalSignSoap12"), VitalSignSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VITALSIGN_EXCEPTION!= null) {
            throw VITALSIGN_EXCEPTION;
        }
        return VITALSIGN_WSDL_LOCATION;
    }

}
