
package com.syntrontech.pmo.pmo.vitalsign;

import java.util.concurrent.Future;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VitalSignSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VitalSignSoap {


    /**
     * 
     * @param vsData
     * @param id
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadVitalSign", action = "http://tempuri.org/UploadVitalSign")
    @WebResult(name = "UploadVitalSignResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadVitalSign", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.UploadVitalSign")
    @ResponseWrapper(localName = "UploadVitalSignResponse", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.UploadVitalSignResponse")
    public String uploadVitalSign(
            @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
                    String pwd,
            @WebParam(name = "VSData", targetNamespace = "http://tempuri.org/")
                    String vsData);
    
    @WebMethod(operationName = "UploadVitalSign", action = "http://tempuri.org/UploadVitalSign")
    @RequestWrapper(localName = "UploadVitalSign", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.UploadVitalSign")
    @ResponseWrapper(localName = "UploadVitalSignResponse", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.UploadVitalSignResponse")
    public Future<?> uploadVitalSign(
            @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
                    String pwd,
            @WebParam(name = "VSData", targetNamespace = "http://tempuri.org/")
                    String vsData,
            AsyncHandler<UploadVitalSignResponse> handler);

    /**
     * 
     * @param vsData
     * @param id
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadVitalRecord", action = "http://tempuri.org/UploadVitalRecord")
    @WebResult(name = "UploadVitalRecordResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadVitalRecord", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.UploadVitalRecord")
    @ResponseWrapper(localName = "UploadVitalRecordResponse", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.UploadVitalRecordResponse")
    public String uploadVitalRecord(
            @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
                    String pwd,
            @WebParam(name = "VSData", targetNamespace = "http://tempuri.org/")
                    String vsData);
    
    @WebMethod(operationName = "UploadVitalRecord", action = "http://tempuri.org/UploadVitalRecord")
    @RequestWrapper(localName = "UploadVitalRecord", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.UploadVitalRecord")
    @ResponseWrapper(localName = "UploadVitalRecordResponse", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.UploadVitalRecordResponse")
    public Future<?> uploadVitalRecord(
            @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
                    String pwd,
            @WebParam(name = "VSData", targetNamespace = "http://tempuri.org/")
                    String vsData,
            AsyncHandler<UploadVitalRecordResponse> handler);

    /**
     * 
     * @param endDate
     * @param id
     * @param pwd
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVitalSign", action = "http://tempuri.org/GetVitalSign")
    @WebResult(name = "GetVitalSignResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVitalSign", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.GetVitalSign")
    @ResponseWrapper(localName = "GetVitalSignResponse", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.GetVitalSignResponse")
    public String getVitalSign(
            @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
                    String pwd,
            @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
                    String endDate);
    
    @WebMethod(operationName = "GetVitalSign", action = "http://tempuri.org/GetVitalSign")
    @RequestWrapper(localName = "GetVitalSign", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.GetVitalSign")
    @ResponseWrapper(localName = "GetVitalSignResponse", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.GetVitalSignResponse")
    public Future<?> getVitalSign(
            @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
                    String pwd,
            @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
                    String endDate,
            AsyncHandler<GetVitalSignResponse> handler);

    /**
     * 
     * @param endDate
     * @param id
     * @param pwd
     * @param type
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVitalRecord", action = "http://tempuri.org/GetVitalRecord")
    @WebResult(name = "GetVitalRecordResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVitalRecord", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.GetVitalRecord")
    @ResponseWrapper(localName = "GetVitalRecordResponse", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.GetVitalRecordResponse")
    public String getVitalRecord(
            @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
                    String pwd,
            @WebParam(name = "Type", targetNamespace = "http://tempuri.org/")
                    String type,
            @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
                    String endDate);
    
    @WebMethod(operationName = "GetVitalRecord", action = "http://tempuri.org/GetVitalRecord")
    @RequestWrapper(localName = "GetVitalRecord", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.GetVitalRecord")
    @ResponseWrapper(localName = "GetVitalRecordResponse", targetNamespace = "http://tempuri.org/", className = "com.syntrontech.syncare.external.pmo.vitalsign.GetVitalRecordResponse")
    public Future<?> getVitalRecord(
            @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
                    String id,
            @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
                    String pwd,
            @WebParam(name = "Type", targetNamespace = "http://tempuri.org/")
                    String type,
            @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
                    String startDate,
            @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
                    String endDate,
            AsyncHandler<GetVitalRecordResponse> handler);

}
